#include "../include/apu.h"

Spc_700::Spc_700()
{
	using ref = Spc_700;

	// 256-entry SPC700 opcode lookup.

	//will take me longer than i think

	lookup =
	{
		// 0                                // 1                                // 2                                // 3                                // 4                                // 5                                // 6                                // 7                                // 8                                // 9                                // A                                // B                                // C                                // D                                // E                                // F
		  {"NOP", &ref::, &ref::, }, {"JSTO", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BBS", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"OR", &ref::, &ref::, }, {"ORC", &ref::, &ref::, }, {"ASL", &ref::, &ref::, }, {"ASL", &ref::, &ref::, }, {"PHP", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BRK", &ref::, &ref::, },    // 0                        
		  {"BPL", &ref::, &ref::, }, {"JST1", &ref::, &ref::, }, {"CLR1", &ref::, &ref::, }, {"BBC", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"ORA", &ref::, &ref::, }, {"OR", &ref::, &ref::, }, {"OR", &ref::, &ref::, }, {"DEW", &ref::, &ref::, }, {"ASL", &ref::, &ref::, }, {"ASL", &ref::, &ref::, }, {"DEX", &ref::, &ref::, }, {"CPX", &ref::, &ref::, }, {"JMP", &ref::, &ref::, },     // 1
		  {"CPL", &ref::, &ref::, }, {"JST2", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BBS", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"ORC", &ref::, &ref::, }, {"ROL", &ref::, &ref::, }, {"ROL", &ref::, &ref::, }, {"PHA", &ref::, &ref::, }, {"CBNE", &ref::, &ref::, }, {"BRA", &ref::, &ref::, },  // 2
		  {"BMI", &ref::, &ref::, }, {"JST3", &ref::, &ref::, }, {"CLR1", &ref::, &ref::, }, {"BBC", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"AND", &ref::, &ref::, }, {"INW", &ref::, &ref::, }, {"ROL", &ref::, &ref::, }, {"ROL", &ref::, &ref::, }, {"INX", &ref::, &ref::, }, {"CPX", &ref::, &ref::, }, {"JSR", &ref::, &ref::, },   // 3
		  {"SEP", &ref::, &ref::, }, {"JST4", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BBS", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EOR", &ref::, &ref::, }, {"ANDC", &ref::, &ref::, }, {"LSR", &ref::, &ref::, }, {"LSR", &ref::, &ref::, }, {"PHX", &ref::, &ref::, }, {"CLR1", &ref::, &ref::, }, {"JSP", &ref::, &ref::, }, // 4
		  {"BVC", &ref::, &ref::, }, {"JST5", &ref::, &ref::, }, {"CLR1", &ref::, &ref::, }, {"BBC", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EORA", &ref::, &ref::, }, {"EOR", &ref::, &ref::, }, {"EOR", &ref::, &ref::, }, {"CPW", &ref::, &ref::, }, {"LSR", &ref::, &ref::, }, {"LSR", &ref::, &ref::, }, {"TAX", &ref::, &ref::, }, {"CPY", &ref::, &ref::, }, {"JMP", &ref::, &ref::, },   // 5
		  {"CLC", &ref::, &ref::, }, {"JST6", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BBS", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"ANDC", &ref::, &ref::, }, {"ROR", &ref::, &ref::, }, {"ROR", &ref::, &ref::, }, {"PHY", &ref::, &ref::, }, {"DBNZ", &ref::, &ref::, }, {"RTS", &ref::, &ref::, },   // 6
		  {"BVS", &ref::, &ref::, }, {"JST7", &ref::, &ref::, }, {"CLR1", &ref::, &ref::, }, {"BBC", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"CMP", &ref::, &ref::, }, {"ADW", &ref::, &ref::, }, {"ROR", &ref::, &ref::, }, {"ROR", &ref::, &ref::, }, {"TXA", &ref::, &ref::, }, {"CPY", &ref::, &ref::, }, {"RTI", &ref::, &ref::, },    // 7
		  {"SEC", &ref::, &ref::, }, {"JST8", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BBS", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"EORC", &ref::, &ref::, }, {"DEC", &ref::, &ref::, }, {"DEC", &ref::, &ref::, }, { "LDY",& ref::,&ref::, }, {"PLP", &ref::, &ref::,}, {"MOV", &ref::, &ref::, },    // 8
		  {"BCC", &ref::, &ref::, }, {"JST9", &ref::, &ref::, }, {"CLR1", &ref::, &ref::, }, {"BBC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"ADC", &ref::, &ref::, }, {"SBW", &ref::, &ref::, }, {"DEC", &ref::, &ref::, }, {"DEC", &ref::, &ref::, }, {"TSX", &ref::, &ref::, }, {"DIV", &ref::, &ref::, }, {"XCN", &ref::, &ref::, },    // 9
		  {"CLI", &ref::, &ref::, }, {"JSTA", &ref::, &ref::, }, {"SET1", &ref::, &ref::, }, {"BBS", &ref::, &ref::, }, {"SBC", &ref::, &ref::, }, {"SBC", &ref::, &ref::, }, {"SBC", &ref::, &ref::, }, {"SBC", &ref::, &ref::, }, {"SBC", &ref::, &ref::, }, {"SBC", &ref::, &ref::, }, {"LDC", &ref::, &ref::, }, {"INC", &ref::, &ref::, }, {"INC", &ref::, &ref::, }, {"CPY", &ref::, &ref::, }, {"PLA", &ref::, &ref::, }, {"STA", &ref::, &ref::, },    // A

	};
}

