#include "../include/cpu.h"
#include "../include/bus.h"
#include "../include/memory.h"

CPU_65816::CPU_65816() {
	using ref = CPU_65816; //referential access

	//opcode lookup
	lookup =
	{    // 0                            //1                               //2                             //3                             //4                             //5                             //6                             //7                               //8                             //9                              //A                             //B                             //C                             //D                             //E                             //F                                                                                  
		{"BRK", &ref::BRK, &ref::ST, 7},{"ORA", &ref::ORA, &ref::DRID, 6},{"COP", &ref::COP, &ref::ST, 7},{"ORA", &ref::ORA, &ref::SR, 4},{"TSB", &ref::TSB, &ref::DR, 3},{"ORA", &ref::ORA, &ref::DR, 3},{"ASL", &ref::ASL, &ref::DR, 5},{"ORA", &ref::ORA, &ref::DRIL, 6},{"PHP", &ref::PHP, &ref::ST, 3},{"ORA", &ref::ORA, &ref::IMM, 2},{"ASL", &ref::ASL, &ref::AC, 2},{"PHD", &ref::PHD, &ref::ST, 4},{"TSB", &ref::TSB, &ref::AC, 6},{"ORA", &ref::ORA, &ref::AC, 4},{"ASL", &ref::ASL, &ref::AC, 6},{"ORA", &ref::ORA, &ref::ABL, 5},  // 0
		{"BPL", &ref::BPL, &ref::RL, 2},{"ORA", &ref::ORA, &ref::DRIIL, 5},{"ORA", &ref::ORA, &ref::DRIL, 5},{"ORA", &ref::ORA, &ref::SRII, 7},{"TRB", &ref::TRB, &ref::DR, 5},{"ORA", &ref::ORA, &ref::DRX, 4},{"ASL", &ref::ASL, &ref::DRX, 6},{"ORA", &ref::ORA, &ref::DRIIL, 6},{"CLC", &ref::CLC, &ref::IMP, 2},{"ORA", &ref::ORA, &ref::ABY, 6},{"INC", &ref::INC, &ref::AC, 2},{"TCS", &ref::TCS, &ref::IMP, 2},{"TRB", &ref::TRB, &ref::AB, 6},{"ORA", &ref::ORA, &ref::ABX, 4},{"ASL", &ref::ASL, &ref::ABX, 7},{"ORA", &ref::ORA, &ref::ABIL, 5},  // 1
		{"JSR", &ref::JSR, &ref::AB, 6},{"AND", &ref::AND, &ref::DRID, 6},{"JSL", &ref::JSL, &ref::ABL, 8},{"AND", &ref::AND, &ref::SR, 4},{"BIT", &ref::BIT, &ref::DR, 3},{"AND", &ref::AND, &ref::DR, 3},{"ROL", &ref::ROL, &ref::DR, 5},{"AND", &ref::AND, &ref::DRIL, 6},{"PLP", &ref::PLP, &ref::ST, 4},{"AND", &ref::AND, &ref::IMM, 2},{"ROL", &ref::ROL, &ref::AC, 2},{"PLD", &ref::PLD, &ref::ST, 5},{"BIT", &ref::BIT, &ref::AB, 4},{"AND", &ref::AND, &ref::AB, 4},{"ROL", &ref::ROL, &ref::AB, 6},{"AND", &ref::AND, &ref::ABL, 5},  // 2
		{"BMI", &ref::BMI, &ref::RL, 2},{"AND", &ref::AND, &ref::DRII, 5},{"AND", &ref::AND, &ref::DRI, 4},{"AND", &ref::AND, &ref::SRII, 7},{"BIT", &ref::BIT, &ref::DRX, 4},{"AND", &ref::AND, &ref::DRX, 4},{"ROL", &ref::ROL, &ref::DRX, 6},{"AND", &ref::AND, &ref::DRIIL, 6}, {"SEC", &ref::SEC, &ref::IMP, 2},{"AND", &ref::AND, &ref::ABY, 4},{"DEC", &ref::DEC, &ref::AC, 2},{"TSC", &ref::TSC, &ref::IMP, 2},{"BIT", &ref::BIT, &ref::ABX, 4},{"AND", &ref::AND, &ref::ABX, 4},{"ROL", &ref::ROL, &ref::ABX, 7},{"AND", &ref::AND, &ref::ABIL, 5},  // 3
		{"RTI", &ref::RTI, &ref::ST, 7},{"EOR", &ref::EOR, &ref::DRID, 6},{"WDM", &ref::WDM, &ref::DRI, 2},{"EOR", &ref::EOR, &ref::SR, 4},{"MVP", &ref::MVP, &ref::BM, 7},{"EOR", &ref::EOR, &ref::DR, 3},{"LSR", &ref::LSR, &ref::DR, 5},{"EOR", &ref::EOR, &ref::DRIL, 6},{"PHA", &ref::PHA,},{"EOR", &ref::EOR,},{"LSR", &ref::LSR,},{"PHK", &ref::PHK,},{"JMP", &ref::JMP,},{"EOR", &ref::EOR,},{"LSR", &ref::LSR,},{"EOR", &ref::EOR,},  // 4
		{"BVC", &ref::BVC, },{"EOR", &ref::EOR, },{"EOR", &ref::EOR, },{"EOR", &ref::EOR, },{"MVN", &ref::MVN, },{"EOR", &ref::EOR, },{"LSR", &ref::LSR, },{"EOR", &ref::EOR, },{"CLI", &ref::CLI, },{"EOR", &ref::EOR, },{"PHY", &ref::PHY, },{"TCD", &ref::TCD, },{"JMP", &ref::JMP, },{"EOR", &ref::EOR, },{"LSR", &ref::LSR, },{"EOR", &ref::EOR, },  // 5
		{"RTS", &ref::RTS, },{"ADC", &ref::ADC, },{"PER", &ref::PER, },{"ADC", &ref::ADC, },{"STZ", &ref::STZ, },{"ADC", &ref::ADC, },{"ROR", &ref::ROR, },{"ADC", &ref::ADC, },{"PLA", &ref::PLA, },{"ADC", &ref::ADC, },{"ROR", &ref::ROR, },{"RTL", &ref::RTL, },{"JMP", &ref::JMP, },{"ADC", &ref::ADC, },{"ROR", &ref::ROR, },{"ADC", &ref::ADC, },  // 6
		{"BVS", &ref::BVS, },{"ADC", &ref::ADC, },{"ADC", &ref::ADC, },{"ADC", &ref::ADC, },{"STZ", &ref::STZ, },{"ADC", &ref::ADC, },{"ROR", &ref::ROR, },{"ADC", &ref::ADC, },{"SEI", &ref::SEI, },{"ADC", &ref::ADC, },{"PLY", &ref::PLY, },{"TDC", &ref::TDC, },{"JMP", &ref::JMP, },{"ADC", &ref::ADC, },{"ROR", &ref::ROR, },{"ADC", &ref::ADC, },  // 7
		{"BRA", &ref::BRA, },{"STA", &ref::STA, },{"BRL", &ref::BRL, },{"STA", &ref::STA, },{"STY", &ref::STY, },{"STA", &ref::STA, },{"STX", &ref::STX, },{"STA", &ref::STA, },{"DEY", &ref::DEY, },{"BIT", &ref::BIT, },{"TXA", &ref::TXA, },{"PHB", &ref::PHB, },{"STY", &ref::STY, },{"STA", &ref::STA, },{"STX", &ref::STX, },{"STA", &ref::STA, },  // 8
		{"BCC", &ref::BCC, },{"STA", &ref::STA, },{"STA", &ref::STA, },{"STA", &ref::STA, },{"STY", &ref::STY, },{"STA", &ref::STA, },{"STX", &ref::STX, },{"STA", &ref::STA, },{"TYA", &ref::TYA, },{"STA", &ref::STA, },{"TXS", &ref::TXS, },{"TXY", &ref::TXY, },{"STZ", &ref::STZ, },{"STA", &ref::STA, },{"STZ", &ref::STZ, },{"STA", &ref::STA, },  // 9
		{"LDY", &ref::LDY, },{"LDA", &ref::LDA, },{"LDX", &ref::LDX, },{"LDA", &ref::LDA, },{"LDY", &ref::LDY, },{"LDA", &ref::LDA, },{"LDX", &ref::LDX, },{"LDA", &ref::LDA, },{"TAY", &ref::TAY, },{"LDA", &ref::LDA, },{"TAX", &ref::TAX, },{"PLB", &ref::PLB, },{"LDY", &ref::LDY, },{"LDA", &ref::LDA, },{"LDX", &ref::LDX, },{"LDA", &ref::LDA, },  // A
		{"BCS", &ref::BCS, },{"LDA", &ref::LDA, },{"LDA", &ref::LDA, },{"LDA", &ref::LDA, },{"LDY", &ref::LDY, },{"LDA", &ref::LDA, },{"LDX", &ref::LDX, },{"LDA", &ref::LDA, },{"CLV", &ref::CLV, },{"LDA", &ref::LDA, },{"TSX", &ref::TSX, },{"TYX", &ref::TYX, },{"LDY", &ref::LDY, },{"LDA", &ref::LDA, },{"LDX", &ref::LDX, },{"LDA", &ref::LDA, },  // B
		{"CPY", &ref::CPY, },{"CMP", &ref::CMP, },{"REP", &ref::REP, },{"CMP", &ref::CMP, },{"CPY", &ref::CPY, },{"CMP", &ref::CMP, },{"DEC", &ref::DEC, },{"CMP", &ref::CMP, },{"INY", &ref::INY, },{"CMP", &ref::CMP, &ref::IMM },{"DEX", &ref::DEX, },{"WAI", &ref::WAI, },{"CPY", &ref::CPY, },{"CMP", &ref::CMP, },{"DEC", &ref::DEC, },{"CMP", &ref::CMP, },  // C
		{"BNE", &ref::BNE, },{"CMP", &ref::CMP, },{"CMP", &ref::CMP, },{"CMP", &ref::CMP, },{"PEI", &ref::PEI, },{"CMP", &ref::CMP, },{"DEC", &ref::DEC, },{"CMP", &ref::CMP, },{"CLD", &ref::CLD, },{"CMP", &ref::CMP, },{"PHX", &ref::PHX, },{"STP", &ref::STP, },{"JML", &ref::JML, },{"CMP", &ref::CMP, },{"DEC", &ref::DEC, },{"CMP", &ref::CMP, },  // D
		{"CPX", &ref::CPX, },{"SBC", &ref::SBC, },{"SEP", &ref::SEP, },{"SBC", &ref::SBC, },{"CPX", &ref::CPX, },{"SBC", &ref::SBC, },{"INC", &ref::INC, },{"SBC", &ref::SBC, },{"INX", &ref::INX, },{"SBC", &ref::SBC, },{"NOP", &ref::NOP, },{"XBA", &ref::XBA, },{"CPX", &ref::CPX, },{"SBC", &ref::SBC, },{"INC", &ref::INC, },{"SBC", &ref::SBC, },  // E
		{"BEQ", &ref::BEQ, },{"SBC", &ref::SBC, },{"SBC", &ref::SBC, },{"SBC", &ref::SBC, },{"PEA", &ref::PEA, },{"INC", &ref::INC, },{"SBC", &ref::SBC, },{"SBC", &ref::SBC, },{"SED", &ref::SED, },{"SBC", &ref::SBC, },{"PLX", &ref::PLX, },{"XCE", &ref::XCE, },{"JSR", &ref::JSR, },{"SBC", &ref::SBC, },{"INC", &ref::INC, },{"SBC", &ref::SBC, }   // F
	};
}